export const SUB_TO_CHANNELS_SCENE = "SUB_TO_CHANNELS:SCENE";
export const ADD_CHANNEL_SCENE = "ADD_CHANNEL:SCENE";
export const CHANNEL_STATS_SCENE = "CHANNEL_STATS:SCENE";
export const CHANGE_TEXT_SCENE = "CHANGE_TEXT:SCENE";
export const CHANGE_LINK_SCENE = "CHANGE_LINK:SCENE"; 
export const GET_REFS_STATS_SCENE = `GET_REFS_STATS:SCENE`;
export const GET_USERS_SCENE = `GET_USERS:SCENE`;